### ISSUE TITLE
Server Stopping

### ISSUE THREAD

**Issue by rytrose** [Calysto/chuck#1]
Hi there!

I'm using these bindings on a Raspberry Pi to sonify two analog data inputs. For some reason I haven't been able to identify, the server stops and exits without error on occasion. This seems to happen most when there are a high volume of requests sent to the ChucK server. Is there a limit of how many messages can be sent to the server in a given time, or total? I've been scouring oscrecv.ck but haven't seen where it's exiting.

**Comment by dsblank** [comment]
I have seen some problems when values are set beyond their limits. But I have never tried with a large number of requests.

The original code was done many years ago by someone familiar with ChucK. I am not familiar... I only did the porting to Python3. So unless someone comes along to help, I am afraid that there is not much that can be done.

If you do find a workaround, please let us know!

**Comment by rytrose** [comment]
I'll check that out, and be sure to let you know if I come across any other issue. Thanks!
